#!/usr/bin/env python3
"""
png_to_lvgl.py - cuts a two-tone pictogram out of its background and writes
it as an LVGL image in A8 format (opacity only, no color).

    python3 tools/png_to_lvgl.py src/fahrrad.png src/img_fahrrad.c \\
            --name img_fahrrad --polarity light --height 131

Why A8 and not RGB565: only opacity is stored, one byte per pixel instead of
two. The color is applied at draw time via the widget style
(`lv_obj_set_style_image_recolor`), so the same pictogram can be rendered
white-on-blue or in any other color without regenerating it.

--polarity light = the light area is the motif (white bicycle on blue)
--polarity dark  = the dark area is the motif (black figures on white)

The motif is cropped to its content and scaled to the target height with
anti-aliasing - which is why this uses A8 rather than 1-bit.
"""

import argparse
import os

import numpy as np
from PIL import Image


def convert(src, dst, name, polarity, height, threshold):
    """
    convert(src, dst, name, polarity, height, threshold) - cut the motif out
    of src, scale it, and write it as an LVGL A8 image C source file to dst.

    Parameters:
      src       - input PNG path
      dst       - output .c path
      name      - C identifier for the generated lv_image_dsc_t / data array
      polarity  - "light" (motif is the lighter area) or "dark" (motif is
                  the darker area)
      height    - target height in pixels; width is scaled to preserve the
                  aspect ratio of the cropped motif
      threshold - gray level (0-255) that separates motif from background
                  before opacity is derived from it

    Any transparent RGBA area is first composited onto white so it counts as
    background, then the image is converted to grayscale. Opacity per pixel
    is derived from how far each gray value lies from `threshold` (in the
    direction the chosen polarity implies), normalized so the darker of the
    two possible ranges (threshold vs. 255-threshold) maps to full 0..255
    opacity. The result is cropped to its bounding box (pixels with opacity
    > 8) and resized to `height` with Lanczos resampling, which is why A8
    (with real alpha gradients) is used instead of a 1-bit mask.
    """
    im = Image.open(src)
    if im.mode == "RGBA":
        # Transparent areas count as background
        bg = Image.new("RGBA", im.size, (255, 255, 255, 255))
        im = Image.alpha_composite(bg, im)
    g = np.asarray(im.convert("L")).astype(np.int16)

    # Opacity: 255 where the motif is
    alpha = (g - threshold) if polarity == "light" else (threshold - g)
    alpha = np.clip(alpha * (255.0 / max(threshold, 255 - threshold)), 0, 255)

    ys, xs = np.where(alpha > 8)
    if len(xs) == 0:
        raise SystemExit(f"{src}: no motif found - wrong polarity?")
    a = alpha[ys.min():ys.max() + 1, xs.min():xs.max() + 1]

    h0, w0 = a.shape
    w = max(1, round(w0 * height / h0))
    img = Image.fromarray(a.astype(np.uint8), "L").resize((w, height),
                                                          Image.LANCZOS)
    data = np.asarray(img).astype(np.uint8)

    body = []
    for row in data:
        body.append("    " + " ".join(f"0x{v:02x}," for v in row))

    with open(dst, "w") as f:
        f.write(f'''/*
 * {os.path.basename(dst)} - generated by tools/png_to_lvgl.py
 * Source: {os.path.basename(src)}, cut out and scaled to {w}x{height}.
 *
 * Format A8: one byte of opacity per pixel, no color. The color is applied
 * at draw time via the style (image_recolor) - so the same bitmap can be
 * rendered white-on-blue or in any other color.
 *
 * Do not edit by hand - re-run the tool instead.
 */

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl.h"
#endif

static const uint8_t {name}_map[] = {{
''')
        f.write("\n".join(body))
        f.write(f'''
}};

const lv_image_dsc_t {name} = {{
    .header.magic = LV_IMAGE_HEADER_MAGIC,
    .header.cf = LV_COLOR_FORMAT_A8,
    .header.flags = 0,
    .header.w = {w},
    .header.h = {height},
    .header.stride = {w},
    .header.reserved_2 = 0,
    .data_size = sizeof({name}_map),
    .data = {name}_map,
    .reserved = NULL,
}};
''')
    print(f"{dst}: {w}x{height} px, {w*height/1024:.1f} KiB "
          f"(original {w0}x{h0})")


def main():
    """
    main() - CLI entry point: parse arguments and call convert().

    No parameters (reads sys.argv via argparse).
    """
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("src")
    ap.add_argument("dst")
    ap.add_argument("--name", required=True)
    ap.add_argument("--polarity", choices=("light", "dark"), required=True)
    ap.add_argument("--height", type=int, default=131)
    ap.add_argument("--threshold", type=int, default=128)
    a = ap.parse_args()
    convert(a.src, a.dst, a.name, a.polarity, a.height, a.threshold)


if __name__ == "__main__":
    main()
